### ISSUE TITLE
Config is no longer being persisted when mod updates occur

### ISSUE THREAD

**Issue by SinZ163** [Floogen/Stardrop#107]
In the last version or two, mod updates resets the config stored in the profile

Stardrop Beta 36
![image](https://user-images.githubusercontent.com/767456/215403282-120ed701-e705-4f86-ba38-17e05f31dad4.png)

**Comment by holy-the-sea** [comment]
Not sure if this is the same, but I have the issue where it constantly tells me that unsaved changes to the config are detected when switching profiles even if I have not, in fact, made any changes. Clicking "Save Configs" before switching also does nothing to remove the problem.

**Comment by Floogen** [comment]
If I am understanding the issue correctly, then I am unfortunately not able to replicate it. I have attempted several mod updates and the profile's config seems to be preserved.

Do you have the steps you took to cause it and could I also request a Stardrop log file for when the issue occurs?

The issue you reported should be resolved with v1.0.0-beta.37, @holy-the-sea. Please do let me know if it still occurs!

**Comment by SinZ163** [comment]
Recording of Camera Pan and MARGO demonstrating the config being reset
https://youtu.be/IHcvzhQqwL8
[log.txt](https://github.com/Floogen/Stardrop/files/11272920/log.txt)

**Comment by holy-the-sea** [comment]
Unfortunately I'm still getting the issue with profile switches with no changes telling me that there are unsaved changes. Should I open a separate issue for this?

**Comment by Floogen** [comment]
If you could that would be great! I will work on both these issues for the next release.

**Comment by voltaek** [comment]
@Floogen Is this still being looked at? Stardrop keeps telling me it will restore my config upon update and then.. not doing so? I don't see anything in the Stardrop `log.txt` file about the config file failing to write, but I also don't see anything about it attempting to write the config file. I see a log entry for every other file of the mod being updated, though. This seems to be the case both for mods updated automatically from Nexus through Stardrop, and for mod ZIPs for updates being dropped onto it manually, such as with UIInfoSuite2.

It's basically
```
[3/25/2024 12:08:09 AM][Debug][MainWindow.AddMods: Line 2067] UIInfoSuite2/manifest.json
[3/25/2024 12:09:04 AM][Debug][MainWindow.AddMods: Line 2146] Install path for mod Annosz.UiInfoSuite2:J:\Steam\SteamApps\common\Stardew Valley\Mods\Stardrop Installed Mods\UIInfoSuite2
[3/25/2024 12:09:04 AM][Debug][MainWindow.AddMods: Line 2164] J:\Steam\SteamApps\common\Stardew Valley\Mods\Stardrop Installed Mods\UIInfoSuite2\manifest.json
```
with the second and third line being repeated for each file in the mod, and then after just these two lines
```
[3/25/2024 12:09:06 AM][Debug][MainWindow.CheckForModUpdates: Line 1712] Attempting to check for mod updates via cache
[3/25/2024 12:09:06 AM][Debug][MainWindow.CheckForModUpdates: Line 1890] Mod update check via cache completed without error
```
and that's it; nothing about restoring a config or anything.

My current settings:
![image](https://github.com/Floogen/Stardrop/assets/7809420/bb68aad0-b6a2-40ee-a55c-e9ccfa982b79)

Let me know if there's anything you want me to try, change, or another log or something that would be useful.
